version: "3"

services:

  postgis:
    image: postgis/postgis:15-3.4
    container_name: spatial_db
    restart: always

    environment:
      POSTGRES_DB: spatial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"
